#!/bin/ksh
pkg="gtk+-2.0 gthread-2.0"
set -x
gcc -I/opt/gmp/include -O3 -march=pentium4 -std=c99 -D_XOPEN_SOURCE -Wall -g -o mandel-gtk $(pkg-config --cflags $pkg) main.c $(pkg-config --libs $pkg) /opt/gmp/lib/libgmp.a || echo >&2 "*** Compile failed!"
