cmdline.o: cmdline.c cmdline.h
file.o: file.c file.h
gtkmandel.o: gtkmandel.c gtkmandel.h mandelbrot.h fpdefs.h defs.h
main.o: main.c cmdline.h file.h fpdefs.h mandelbrot.h gtkmandel.h defs.h
mandelbrot.o: mandelbrot.c cmdline.h mandelbrot.h fpdefs.h
test_parser.o: test_parser.c
